SELECT DATEDIFF(end_date,start_date) AS total_days
FROM projects;

SELECT DATE_ADD(CURDATE(), INTERVAL 30 DAY) AS expiry_date;

SELECT DATE_SUB(CURDATE(), INTERVAL 7 DAY);

SELECT *
FROM orders
WHERE DAYOFWEEK(created_at) IN (1,7);

SELECT MONTHNAME(STR_TO_DATE('15-04-2025','%d-%m-%Y'));